esphome:
  name: genvex-2

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

# Include external components
external_components:
  - source:
      type: git
      url: https://github.com/BenjaminJensen/esphome/

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "89StKipZtoevvy8i/ocFmAgzjltyodL4uQH2RrOfEVQ="

ota:
  password: "Benster101!"

wifi:
  ssid: "Boing"
  password: "benster101"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Genvex-2 Fallback Hotspot"
    password: "FhIltHcpNB7T"

captive_portal:

sensor:
  - platform: rpm_hw_sensor
    rpm1:
      name: "RPM 1"
    rpm2:
      name: "RPM 2"

switch:
  - platform: gpio
    name: "Fan Power Relay"
    pin: 
      number: 2
      inverted: true
    icon: "mdi:power-cycle"
  - platform: gpio
    name: "Rotor Relay"
    pin: 
      number: 4
      inverted: true
    icon: "mdi:reload"

output:
- platform: float_relay_ladder
  id: float_relay_ladder_1

fan:
  - platform: speed
    output: float_relay_ladder_1
    name: "LVAR75"
    speed_count: 5