# Basic Config
substitutions:
  friendly_name: Genvex Power
  device_name: genvex-power

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  
esp32:
  board: nodemcu-32s

wifi:
  ssid: Boing
  password: benster101
  ap:
    ssid: ${device_name}
    password: Niwz5UY3nAZF

captive_portal:

logger:

api:

ota:
  password: "Benster101!"

#optional
web_server:
  port: 80

uart:
  rx_pin: GPIO16
  baud_rate: 4800
  
sensor:
  - platform: cse7766
    update_interval: 10s
    current:
      name: ${friendly_name} Current
      id: a_sensor
    voltage:
      name: ${friendly_name} Voltage
      id: v_sensor
    power:
      name: ${friendly_name} Power
      id: w_sensor
      on_value_range:
        - above: 4.0
          then:
            - light.turn_on: switch_led
        - below: 3.0
          then:
            - light.turn_off: switch_led
    energy:
      name: ${friendly_name} Energy
      id: wh_sensor

output:
  - platform: ledc
    id: led
    pin:
      number: GPIO18
      inverted: True

light:
  - platform: monochromatic
    id: switch_led
    output: led
    internal: True
  - platform: status_led
    id: wifi_status_led
    internal: True
    pin:
      number: GPIO05
      inverted: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${friendly_name} - Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${friendly_name} - Relay Switch"
    pin: GPIO13
    id: relay